name: cicd
on:
  pull_request:
    types: [ opened, reopened, synchronize]
  release:
    types: [ published ]

env:
  python-version-latest: "3.12"

defaults:
  run:
    shell: bash

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Prepare artefacts
        run: |
          pip install --no-cache-dir -U pip
          pip install --no-cache-dir -U poetry
          poetry install --no-root
          pre-commit run --all-files
          poetry build
          pip install --no-cache-dir -U dist/*.whl
      - name: Run tests
        run: pytest --showlocals -vv --cov
      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags') && matrix.python-version == env.python-version-latest
        with:
          name: dist-${{ matrix.python-version }}
          path: dist/

  cd:
    # https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
    needs: [ ci ]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artefacts
        uses: actions/download-artifact@v4
        with:
          name: dist-${{ env.python-version-latest }}
          path: dist/
      - name: Publish distribution 📦 to Test PyPI
        if: github.event.release.prerelease == true
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TESTPYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
        if: github.event.release.prerelease == false
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
